#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
site 'http://community.opscode.com/api/v1'
cookbook 'git', '~> 4.1.0'

cookbook 'ssh_known_hosts', '~> 2.0.0'
cookbook 'nodejs', '~> 2.2.0'


# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
